from django.urls import path,include
from . import views
from .views import awardee

urlpatterns = [
    path('', views.index, name='index'),
    path('awardee/', views.awardee, name='awardee'),
    path('pay', views.pay, name='pay'),
    path('actyuli', views.actyuli, name='actyuli'),
    path('actorigba', views.actorigba, name='actorigba'),
    path('actressuli', views.actressuli, name='actressuli'),
    path('actressigba', views.actressigba, name='actressigba'),
    path('mostinigba', views.mostinigba, name='mostinigba'),
    path('mostiniuli', views.mostinuli, name='mostinuli'),
    path('mostbigba', views.mostbigba, name='mostbigba'),
    path('mostbuli', views.mostbuli, name='mostbuli'),
    path('stdiigba', views.stdiigba, name='stdiigba'),
    path('stdiuli', views.stdiuli, name='stdiuli'),
    path('maigba', views.maigba, name='maigba'),
    path('mauli', views.mauli, name='mauli'),
    path('eveigba', views.eveigba, name='eveigba'),
    path('eveuli', views.eveuli, name='eveuli'),
    path('fmaigba', views.fmaigba, name='fmaigba'),
    path('fmauli', views.fmauli, name='fmauli'),
    path('stddjigba', views.stddjigba, name='stddjigba'),
    path('stddjuli', views.stddjuli, name='stddjuli'),
    path('fctigba', views.fctigba, name='fctigba'),
    path('fctuli', views.fctuli, name='fctuli'),
    path('matuli', views.matuli, name='matuli'),
    path('matuigba', views.matigba, name='matigba'),
    path('fmtigba', views.fmtigba, name='fmtigba'),
    path('fmtuli', views.fmtuli, name='fmtuli'),
    path('matuigba', views.matigba, name='matigba'),
    path('contentigba', views.contentigba, name='contentigba'),
    path('contentuli', views.contentuli, name='contentuli'),
    path('matuigba', views.matigba, name='matigba'),
    path('comuli', views.comuli, name='comuli'),
    path('comigba', views.comigba, name='comigba'),
    path('skitigba', views.skitigba, name='skitigba'),
    path('skituli', views.skituli, name='skituli'),
    path('hypemanigba', views.hypemanigba, name='hypemanigba'),
    path('hypemanuli', views.hypemanuli, name='hypemanuli'),
    path('schigba', views.schigba, name='schigba'),
    path('schuli', views.schuli, name='schuli'),
    path('spigba', views.spigba, name='spigba'),
    path('spuli', views.spuli, name='spuli'),
    path('mmigba', views.mmigba, name='mmigba'),
    path('mmuli', views.mmuli, name='mmuli'),
    path('fmigba', views.fmigba, name='fmigba'),
    path('fmuli', views.fmuli, name='fmuli'),
    path('stpigba', views.stpigba, name='stpigba'),
    path('stpuli', views.stpuli, name='stpuli'),
    path('stppigba', views.stppigba, name='stppigba'),
    path('stppuli', views.stppuli, name='stppuli'),
    path('stvigba', views.stvigba, name='stvigba'),
    path('stvuli', views.stvuli, name='stvuli'),
    path('courseigba', views.courseigba, name='courseigba'),
    path('courseuli', views.courseuli, name='courseuli'),
    path('mdigba', views.mdigba, name='mdigba'),
    path('mduli', views.mduli, name='mduli'),
    path('fmdigba', views.fmdigba, name='fmdigba'),
    path('fmduli', views.fmduli, name='fmduli'),
    path('otyuli', views.otyigba, name='otyuli'),
    path('otyigba', views.otyigba, name='otyigba'),
    

    
]


 