# Generated by Django 4.2.3 on 2023-07-15 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='App',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('carousel1', models.ImageField(upload_to='carousel')),
                ('carousel2', models.ImageField(upload_to='carousel')),
                ('title', models.CharField(max_length=50)),
                ('categories', models.ImageField(upload_to='categories')),
                ('pictures', models.ImageField(upload_to='pics')),
                ('banner', models.ImageField(upload_to='banner')),
                ('logo', models.ImageField(upload_to='logo')),
                ('copyright', models.CharField(max_length=50)),
            ],
        ),
    ]
