# Generated by Django 4.2.3 on 2023-07-15 23:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentchoice', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='app',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='app',
            name='name',
        ),
        migrations.RemoveField(
            model_name='app',
            name='pictures',
        ),
    ]
