# Generated by Django 4.2.3 on 2023-07-16 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentchoice', '0003_awardee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awardee',
            name='description',
            field=models.CharField(max_length=50),
        ),
    ]
