# Generated by Django 4.2.3 on 2023-07-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentchoice', '0004_alter_awardee_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='awardee',
            name='images',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
