# Generated by Django 4.2.3 on 2023-07-19 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentchoice', '0008_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
