# Generated by Django 4.2.3 on 2023-07-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentchoice', '0011_alter_category_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='details',
        ),
    ]
