# Generated by Django 4.2.3 on 2023-07-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentchoice', '0012_remove_category_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture1', models.ImageField(upload_to='nominees')),
                ('picture2', models.ImageField(upload_to='nominees')),
                ('picture3', models.ImageField(upload_to='nominees')),
                ('picture4', models.ImageField(upload_to='nominees')),
                ('picture5', models.ImageField(upload_to='nominees')),
                ('picture6', models.ImageField(upload_to='nominees')),
                ('picture7', models.ImageField(upload_to='nominees')),
                ('picture8', models.ImageField(upload_to='nominees')),
                ('picture9', models.ImageField(upload_to='nominees')),
                ('picture10', models.ImageField(upload_to='nominees')),
                ('picture11', models.ImageField(upload_to='nominees')),
                ('picture12', models.ImageField(upload_to='nominees')),
                ('picture13', models.ImageField(upload_to='nominees')),
                ('picture14', models.ImageField(upload_to='nominees')),
                ('picture15', models.ImageField(upload_to='nominees')),
                ('picture16', models.ImageField(upload_to='nominees')),
                ('picture17', models.ImageField(upload_to='nominees')),
                ('picture18', models.ImageField(upload_to='nominees')),
                ('picture19', models.ImageField(upload_to='nominees')),
                ('picture20', models.ImageField(upload_to='nominees')),
                ('picture21', models.ImageField(upload_to='nominees')),
                ('picture22', models.ImageField(upload_to='nominees')),
                ('picture23', models.ImageField(upload_to='nominees')),
                ('picture24', models.ImageField(upload_to='nominees')),
                ('picture25', models.ImageField(upload_to='nominees')),
                ('picture26', models.ImageField(upload_to='nominees')),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='picture',
        ),
    ]
