# Generated by Django 4.2.3 on 2023-07-20 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentchoice', '0013_pictures_remove_category_picture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pictures',
        ),
        migrations.AddField(
            model_name='category',
            name='details',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='picture',
            field=models.ImageField(null=True, upload_to='nominees'),
        ),
    ]
